# fly.toml app configuration file generated for hbd-line-bot on 2025-04-07T17:19:08+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hbd-line-bot'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
